name: minimum-review-bot
namespace: internal
image:
  repository: bufferapp/minimum-review-bot
replicaCount: 1
ingress:
  enabled: true
  host: minimum-review-bot.buffer.com
  path: /
env:
  # remove this when we update to helm 2.9.0+
  - name: APP_ID
    value: !!str 15448
healthcheck:
  enabled: true
  config:
    port: 8086
    livenessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000/probot
    readinessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000/probot
