name: minimum-review-bot
namespace: internal
image:
  repository: bufferapp/minimum-review-bot
replicaCount: 1
ingress:
  enabled: true
  host: minimum-review-bot.buffer.com
  path: /
env:
  - name: APP_ID
    value: !!str 15448
  - name: PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: minimum-review-bot-private-key
        key: minimum-review-bot.private-key.pem
healthcheck:
  enabled: true
  config:
    port: 8086
    livenessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000/probot
    readinessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000/probot
